AuthenticationAndAuthorization/MVCApp/Models/ErrorViewModel.cs
namespace MVCApp.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

AuthenticationAndAuthorization/MVCApp/Models/SignInDto.cs
namespace MVCApp.Models;

public class SignInDto
{
    public string Username { get; set; } = String.Empty;
    public string Password { get; set; } = String.Empty;
    public bool RememberMe { get; set; }
}

AuthenticationAndAuthorization/MVCApp/Controllers/AdminController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace MVCApp.Controllers;

[Authorize]
public class AdminController : Controller
{
    private readonly ILogger<AdminController> _logger;

    public AdminController(ILogger<AdminController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

}

AuthenticationAndAuthorization/MVCApp/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace MVCApp.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

}

AuthenticationAndAuthorization/MVCApp/Controllers/HrOnlyController.cs
using Microsoft.AspNetCore.Mvc;

namespace MVCApp.Controllers;

public class HrOnlyController : Controller
{
    private readonly ILogger<HrOnlyController> _logger;

    public HrOnlyController(ILogger<HrOnlyController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

}

AuthenticationAndAuthorization/MVCApp/Controllers/ManagerController.cs
using Microsoft.AspNetCore.Mvc;

namespace MVCApp.Controllers;

public class ManagerController : Controller
{
    private readonly ILogger<ManagerController> _logger;

    public ManagerController(ILogger<ManagerController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

}

AuthenticationAndAuthorization/MVCApp/Controllers/NotFoundController.cs
using Microsoft.AspNetCore.Mvc;

namespace MVCApp.Controllers;

public class NotFoundController : Controller
{
    public IActionResult Index()
    {
        return View();
    }
}

AuthenticationAndAuthorization/MVCApp/Controllers/SignInController.cs
using System.Security.Claims;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using MVCApp.Models;

namespace MVCApp.Controllers;

public class SignInController : Controller
{
    public IActionResult Index()
    {
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> VerifyUserCredentials(SignInDto signInDto)
    {
        if (!ModelState.IsValid) return View("Index");

        if (User.Identity is not null && !User.Identity.IsAuthenticated)
        {
            List<Claim> claims = GetUserClaimsList(signInDto);
            var identity = new ClaimsIdentity(claims, "MyCookieAuth");
            var principal = new ClaimsPrincipal(identity);

            var authenticationProperties = new AuthenticationProperties()
            {
                IssuedUtc = DateTime.UtcNow,
                IsPersistent = signInDto.RememberMe
            };

            await HttpContext.SignInAsync("MyCookieAuth", principal, authenticationProperties);
            return Redirect($"/Admin/Index/");
        }
        else
        {
            await Task.CompletedTask;
            return Redirect($"NotFound/Index");
        }
    }

    private List<Claim> GetUserClaimsList(SignInDto signInDto)
    {
        if (signInDto.Username == "admin")
        {
            return new List<Claim>()
            {
                new Claim(ClaimTypes.Name, "Admin"),
                new Claim(ClaimTypes.Email, "Admin@gmail.com"),
                new Claim("Department", "Admin"),
                new Claim("EmploymentDate", "2024-01-25"),
                new Claim("Admin", "true")
            };
        } else if (signInDto.Username == "hr")
        {
            return new List<Claim>()
            {
                new Claim(ClaimTypes.Name, "HR"),
                new Claim(ClaimTypes.Email, "HR@gmail.com"),
                new Claim("Department", "HR"),
                new Claim("EmploymentDate", "2024-01-25"),
                new Claim("Hr", "true")
            };
        }
        else
        {
            return new List<Claim>()
            {
                new Claim(ClaimTypes.Name, "Valid User"),
                new Claim(ClaimTypes.Email, "Valid@gmail.com"),
                new Claim("Department", "Valid"),
                new Claim("EmploymentDate", "2024-01-25"),
            };
        }
    }
}

AuthenticationAndAuthorization/MVCApp/Views/Admin/Index.cshtml
@model dynamic

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<h2>Admin page</h2>

AuthenticationAndAuthorization/MVCApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<h1>This page is open to all</h1>

AuthenticationAndAuthorization/MVCApp/Views/HrOnly/Index.cshtml
@model dynamic

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<h2>HR Only</h2>

AuthenticationAndAuthorization/MVCApp/Views/Manager/Index.cshtml
@model dynamic

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<h2>Manager Page</h2>

AuthenticationAndAuthorization/MVCApp/Views/NotFound/Index.cshtml
@model dynamic

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<h2>PAGE NOT Found</h2>

AuthenticationAndAuthorization/MVCApp/Views/SignIn/Index.cshtml
@using System.Collections.Specialized
@model dynamic

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<h1> This page is open to all</h1>

<div class="container">
    <div style="width: 500px">
        <form id="signInForm" action="@Url.Action("VerifyUserCredentials", "SignIn")" method="post" >
            <div class="row">
                <input type="text" name="username" placeholder="Enter Username" value="test"/>
            </div>
            <div class="row">
                <input type="password" name="password" placeholder="Enter Password" value="test"/>
            </div>

            <div>
                <input type="checkbox" value="true" name="rememberMe"/>
                <label>Remember Me</label>
            </div>
            <button type="submit">Login</button>
        </form>
    </div>
</div>

@section ScriptsAfter
{
<script src="js/SignIn.js"></script>
}